config/routes.rb
Rails.application.routes.draw do

  resources :dashboard, :configuration
  root to: 'dashboard#home'
  get '/graph' => 'dashboard#graph'
  get '/testcase' => 'dashboard#testcase'
  get '/pagetiming' => 'dashboard#pagetiming'
  get '/qalib' => 'dashboard#qalib'
  get '/view' => 'configuration#view'

end

app/models/awoconfiguration.rb
class Awoconfiguration < ActiveRecord::Base
  establish_connection :qa5_db
  self.table_name = 'live_ks.d_loc'
end

app/models/dashboard.rb
module Dashboard
  class Dashboard < ActiveRecord::Base
    establish_connection :development
    self.table_name = 'app_status'
  end

  class TestCase < ActiveRecord::Base
    establish_connection :development
    self.table_name = 'test_cases'
    self.primary_key='id'
    # has_many :testresults
  end

  class TestResult < ActiveRecord::Base
    establish_connection :development
    self.table_name = 'awo_sessions'
    self.primary_key = 'id'
    # belongs_to :testcase
    # :foreign_key => "case_id"

  end

  class SimpleGraph < ActiveRecord::Base
    establish_connection :development
    self.table_name = 'awo_sessions'
    self.primary_key = 'id'
  end

  class PageTiming < ActiveRecord::Base

    establish_connection :development
    self.table_name = 'page_timing'
    # belongs_to :testcase
    # :foreign_key => "case_id"
  end

  class QALib < ActiveRecord::Base
    establish_connection :development
    self.table_name = 'code_base_lib'

    def self.search(search)
      where("cb_base_class LIKE ?","%#{search}%")
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awoconfiguration_controller.rb
class AWOConfigurationController < ApplicationController
  # add contract as param later
  def index

  end
  def view
    @result=Awoconfiguration.all.select("desc,name")#.from("D_LOC")
  end
  def syst_1
    #@result=Configuration.select("desc,name").from("D_LOC")
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    @dashsubquery = Dashboard::Dashboard.select("*")
    @dashsubquery = @dashsubquery.order("date desc")
    @dashboard = Dashboard::Dashboard.select("env, build_version, db, status, date")
    .from("(#{@dashsubquery.to_sql}) as temp")
    .group("env")
    .order("date asc")
    #  @list = ReportDashboard.select("casename") #.where(id: 10)
    #   @list_count = @list.count
    #   @subquery = TestResult.select("*")
    #   @subquery = @subquery.order("create_date desc")
    #   @testresult = TestResult.select("case_id, case_name, machine, awo_version, test_result")
    #                     .from("(#{@subquery.to_sql}) as temp")
    #                     .where("case_name".match("%migrauto%")).group("case_name")
    #                     .order("create_date desc")
  end

  def graph()
#    @testenv=dash_params[:testenv]
    @subquery = Dashboard::TestResult.select("*")
    @subquery = @subquery.order("create_date desc")
    @testresult = Dashboard::TestResult.select("case_id, substring(case_name,57) as casename, awo_version,
                        upper(left(contract,2)) as contract, create_date,
                        if(ifnull(test_result, 1)=2, 'Pass', 'Fail') as test_result")
                      .from("(#{@subquery.to_sql}) as temp")
                      .where("awo_version like '%lvmig%' AND case_id <> 0")
                      .group("case_name")
                      .order("awo_version, create_date desc")
  end

  def testcase
    @list = Dashboard::TestCase.select("id, substring(casename,32) as casename, timing")
                .where("test_set='sanity' AND casename not like '%draft%' AND casename not like '%batch%'")
                .order("casename asc")
    @list_count = @list.count(:id)
  end

  def simplegraph

  end

  def dash_params
#    params.require(:graph).permit(:id, :testenv)
  end

  def pagetiming
    @subquery = Dashboard::PageTiming.select("*")
                    .where("recorddate > '2016-01-01 00:00:00'")
                    .order("recorddate desc")
    # @subquery=@subquery
    @result = Dashboard::PageTiming.select("pagename, loadingtime, buildversion,
                  max(recorddate) as latestrecorddate, env,
                  substring(testcasename, 57) as casename")
                  .from("(#{@subquery.to_sql}) as temp")
                  .where("loadingtime > 20 AND testcasename not like '%draft%' AND testcasename not like '%batch%'")
                  .group("pagename, env, buildversion")
                  .order("pagename, buildversion, loadingtime desc")
  end

  def qalib
    @qalib = Dashboard::QALib.none
    if params[:search]
      @qalib = Dashboard::QALib.search(params[:search]).order("cb_class, cb_id")
    else
      @qalib = Dashboard::QALib.none
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
  def configviewlayout
    #key.value
    #key is the spreadsheet, value is the column name


  end
  def configquery

  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def bool_to_glyph(value)
 #     value ? "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span>".html_safe : "<span class='glyphicon glyphicon-remove' aria-hidden='true'></span>".html_safe
      if value=="Down"
        "<span class='glyphicon glyphicon-remove' aria-hidden='true'></span>".html_safe

      elsif value=="Unavailable"
        "<span class='glyphicon glyphicon-warning-sign' aria-hidden='true'></span>".html_safe

      else
        "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span>".html_safe


      end

  end
  def exedecryptoutil(arg2)
    arg1="com.activenetwork.qa.awo.testcases.AwoCryptoUtil"
    result = `java -cp "C:\\migrtest\\Migrtest\\*;" #{arg1} "#{arg2}"`
    return result
  end


end

app/views/configuration/view.html.erb
<!DOCTYPE html>
<html>
<div class="container" style="padding-top: 70px">
  <h2>Configuration</h2>
  <%= form_tag :controller => 'configuration', :action => 'view', :method => 'post' do %>
      <select name="contract">
        <option value="ks" selected="selected">KS</option>
        <option value="co">CO</option>
      </select>
  <% end %>
  <table class="table">
    <tr>
      <th>Description</th>
      <th>Name</th>
    </tr>

    <% @result.each() do |l| %>
        <tr>
          <td><%= l.case_id %></td>
          <td><%= l.casename %></td>

        </tr>
    <% end %>
  </table>

</div>

</html>

app/views/dashboard/graph.html.erb
<!DOCTYPE html>
<html>
<div class="container" style="padding-top: 70px">
  <h2> Test Result</h2>
  <%= form_tag :controller => 'dashboard', :action => 'graph', :method => 'post' do %>
      <select name="testenv">
        <option value="qa5" selected="selected">qa5</option>
        <option value="lvmig">lvmig</option>
      </select>
  <% end %>
  <%= form_tag :controller => 'dashboard', :action => 'graph', :method => 'post' do %>
      <select name="contract">
        <option value="ks" selected="selected">KS</option>
        <option value="co">CO</option>
      </select>
  <% end %>
  <table class="table">
    <tr>
      <th>CaseID</th>
      <th>CaseName</th>
      <th>Version</th>
      <th>Contract</th>
      <th>ExeDate</th>
      <th>TestResult</th>
    </tr>

    <% @testresult.each() do |l| %>
        <tr>
          <td><%= l.case_id %></td>
          <td><%= l.casename %></td>
          <td><%= l.awo_version %></td>
          <td><%= l.contract %></td>
          <td><%= l.create_date %></td>
          <td><%= l.test_result %></td>
        </tr>
    <% end %>
  </table>

</div>

</html>

app/views/dashboard/home.html.erb
<!DOCTYPE html>
<html>
<div class="container">
<div class="jumbotron">
  <p class="lead">
  <h2>Welcome to Migration Automation Dashboard!</h2>
  </p>
</div>

  <table class="table">
    <tr>
      <th>Env</th>
      <th>Build Ver.</th>
      <th>DB</th>
      <th>Status</th>
      <th>Date</th>
    </tr>
    <% @dashboard.each() do |d| %>
        <tr>
          <td><%= d.env %></td>
          <td><%= d.build_version %></td>
          <td><%= d.db %></td>
          <td><%= bool_to_glyph(d.status) %></td>
          <td><%= d.date %></td>
        </tr>

    <% end %>
    </table>
</div>
</html>

app/views/dashboard/pagetiming.html.erb
<!DOCTYPE html>
<html>

<div class="container" style="padding-top: 70px">

  <h2>Slow Page List</h2>
  <%= form_tag :controller => 'dashboard', :action => 'pagetiming', :method => 'post' do %>
      <select name="testenv">
        <option value="qa5" selected="selected">qa5</option>
        <option value="lvmig">lvmig</option>
      </select>
<% end %>
  <table class="table">
    <tr>
      <th>PageName</th>
      <th>LoadingTime</th>
      <th>BuildVersion</th>
      <th>RecordDate</th>
      <th>ENV</th>
      <th>CaseName</th>
    </tr>
    <% @result.each() do |c| %>
        <tr>
          <td><%= c.pagename %></td>
          <td><%= c.loadingtime %></td>
          <td><%= c.buildversion %></td>
          <td><%= c.latestrecorddate %></td>
          <td><%= c.env %></td>
          <td><%= c.casename %></td>
        </tr>

    <% end %>

  </table>


</div>
</html>

app/views/dashboard/qalib.html.erb
<!DOCTYPE html>
<html>

<div class="container" style="padding-top: 70px">

  <h2>Code Base Lib</h2>
  <%= form_tag(qalib_path, :method => "get", id: "cb-search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Code Base" %>
      <%= submit_tag "Search" %>
  <% end %>
<hr />
  <table class="table">
    <tr>
      <th>CB_ID</th>
      <th>CB_NAME</th>
      <th>CB_CLASS</th>
      <th>CB_BASE_CLASS</th>
    </tr>
    <% @qalib.each() do |s| %>
      <tr>
        <td><%= s.cb_id %></td>
        <td><%= s.cb_name %></td>
        <td><%= s.cb_class %></td>
        <td><%= s.cb_base_class %></td>

      </tr>
    <% end %>
  </table>
  <div>
    <%= form_tag(qalib_path, :method => "get", id: "cb-search-form") do %>
        <%= text_field_tag 'idcode', nil, placeholder: 'Input Encryption Code'%>
        <%= submit_tag "Decode" %>

    <% end %>
    <p>
      <%= exedecryptoutil(params[:idcode]) %>
    </p>



  </div>

</div>
</html>

app/views/dashboard/testcase.html.erb
<!DOCTYPE html>
<html>

<div class="container" style="padding-top: 70px">
  <h2>Test Cases #</h2>
  <ul id="casecount">
    <li><%= @list_count %></li>
  </ul>
  <h2>Test Cases List</h2>
  <%= form_tag :controller => 'dashboard', :action => 'testcase', :method => 'post' do %>
      <select name="application">
        <option value="lm" selected="selected">LM</option>
        <option value="im">IM</option>
        <option value="cui">CUI</option>
      </select>
  <% end %>

  <table class="table">
    <tr>
      <th>CaseID</th>
      <th>CaseName</th>
      <th>Timing</th>
    </tr>
    <% @list.each() do |c| %>
        <tr>
          <td><%= c.id %></td>
          <td><%= c.casename %></td>
          <td><%= c.timing %></td>
        </tr>

    <% end %>

  </table>


</div>
</html>

app/views/layouts/_footer.html.erb
<div class="container" style="text-align:center">
  <hr>
  <p>@ ActiveNetwork 2016</p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(graph_path) %>"><%= link_to "Graph", graph_path %></li>
        <li class="<%= 'active' if current_page?(testcase_path) %>"><%= link_to "TestCase",testcase_path %></li>
        <li class="<%= 'active' if current_page?(pagetiming_path) %>"><%= link_to "PageTiming",pagetiming_path %></li>
        <li class="<%= 'active' if current_page?(qalib_path) %>"><%= link_to "QALIB",qalib_path %></li>
        <li class="<%= 'active' if current_page?(view_path) %>"><%= link_to "View",view_path %></li>

      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutomationTestDashboard</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>